// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Subscription struct {
	ID      int64
	UserID  int64
	Players string
	Mode    string
}

type User struct {
	ID                      int64
	TelegramID              sql.NullInt64
	Email                   sql.NullString
	SubscriptionDestination string
}
